# fix

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "aad3e56794b7"
down_revision: str | None = "3d7dc90b4f8c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "event_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "event_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
