
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a37913975f52"
down_revision: str | None = "e04674db9cdf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task_notes", "description", existing_type=sa.VARCHAR(), nullable=True,
    )
    op.drop_column("task_notes", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_notes", sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.alter_column(
        "task_notes", "description", existing_type=sa.VARCHAR(), nullable=False,
    )
    # ### end Alembic commands ###
