# fix users

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "aa0c9d03aa05"
down_revision: str | None = "7b4202214e84"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "group_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=255), nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=255), nullable=False,
    )
    op.alter_column("users", "group_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
