name: "Tests"

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  uv:
    runs-on: ubuntu-latest
    name: uv
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Check lock file
        run: uv lock --check

  ruff:
    runs-on: ubuntu-latest
    name: ruff
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ruff
        uses: astral-sh/ruff-action@v3

      - name: Run ruff
        run: ruff check .

  mypy:
    runs-on: ubuntu-latest
    name: mypy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Run mypy
        run: uv run mypy .